name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build library
        run: |
          cd packages/docker-control
          npx tsc src/index.ts --outDir dist --declaration --module commonjs --target ES2020 --esModuleInterop --skipLibCheck
      
      - name: Run tests
        run: npm test -w @org/docker-control
      
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          directory: ./packages/docker-control/coverage
          flags: unittests
          name: codecov-umbrella

  build-demo:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build library
        run: |
          cd packages/docker-control
          npx tsc src/index.ts --outDir dist --declaration --module commonjs --target ES2020 --esModuleInterop --skipLibCheck
      
      - name: Test demo
        run: |
          cd demo
          npm install
          node test-terminal.js || true
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: library-build
          path: packages/docker-control/dist/

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
      
      - name: Run npm audit
        run: npm audit --audit-level=moderate || true